// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJSpDy8p0pSvqHjZGVkXruCbHQbR1gzxA',
    appId: '1:1051607877494:web:7f408f896487be44f05c57',
    messagingSenderId: '1051607877494',
    projectId: 'loginapp-796b3',
    authDomain: 'loginapp-796b3.firebaseapp.com',
    storageBucket: 'loginapp-796b3.appspot.com',
    measurementId: 'G-ND4DQPWWDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbaIwAQOdGAqeqrSuEs2YySsaMIjblhuE',
    appId: '1:1051607877494:android:7c769f7b8c2b788ef05c57',
    messagingSenderId: '1051607877494',
    projectId: 'loginapp-796b3',
    storageBucket: 'loginapp-796b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjeQhWhiE4UHRXycXgY5gSwlsp2BPhQiU',
    appId: '1:1051607877494:ios:0752e9980985d269f05c57',
    messagingSenderId: '1051607877494',
    projectId: 'loginapp-796b3',
    storageBucket: 'loginapp-796b3.appspot.com',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjeQhWhiE4UHRXycXgY5gSwlsp2BPhQiU',
    appId: '1:1051607877494:ios:0752e9980985d269f05c57',
    messagingSenderId: '1051607877494',
    projectId: 'loginapp-796b3',
    storageBucket: 'loginapp-796b3.appspot.com',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJSpDy8p0pSvqHjZGVkXruCbHQbR1gzxA',
    appId: '1:1051607877494:web:0190b3f80acf90c0f05c57',
    messagingSenderId: '1051607877494',
    projectId: 'loginapp-796b3',
    authDomain: 'loginapp-796b3.firebaseapp.com',
    storageBucket: 'loginapp-796b3.appspot.com',
    measurementId: 'G-1LJ79PMK5G',
  );


}


